str2 = "".join(["The shapeless feelings deep that I possess to cherish forever ",
"I just deleted the templates in my mind to clear my heart ",
"I caught this little phrase that flew by and put it inside my heart ",
"and put my intimate words to sing and shot it out ",
"to break through the sky ",
"It is all the things to share and bare with your heart ",
"It is all the things to shout and send to your heart ",
"Then all the dots combine into one line and ",
"they echo faraway across the distance ",
"It is all the words to share and bear with your heart ",
"It is all the notes to shout and send to your heart ",
"Then all the lines combine into a circle ",
"Comes down to one ",
"to tell your world It is here and everywhere ",
"The crystal clear light that fills the air it always resembles you ",
"Voices slipping through the fingers that I held toward the light ",
"I felt this rhythm through my fingers moving and it came suddenly ",
"Grasping all the words I could find and shout it out to break through the sky ",
"It is all the things to share and bare with your heart ",
"It is all the things to shout and send to your heart ",
"Then all the dots combine into one line and ",
"They sing through out the sky beyond the distance ",
"It is all the words to share and bear with your heart ",
"It is all the notes to shout and send to your heart ",
"Then all the lines combine into a circle ",
"Comes down to one ",
"to tell your world It is here and everywhere ",
"Never doubted the days the sound that I played ",
"I always thought the morning light ",
"It was such an easy gift that will come and simply pour and rain on me ",
"But still the sound that ",
"came and made me believe ",
"It would shake my atmosphere ",
"Tell Your World today ",
"The sound inside within your heart ",
"It is all the things to share and bare with your heart ",
"It is all the things to shout and send to your heart ",
"Then all the dots combine into one line ",
"and they echo faraway across the distance ",
"It is all the words to share and bear with your heart ",
"It is all the notes to shout and send to your heart ",
"Then all the lines combine into a circle ",
"Comes down to one ",
"to tell your world It is here and everywhere "])
if __name__ == "__main__":
    print(str2)