actions_list=[
    "create_fake_signature",
    "insert_useless_data_to_end",
    "modify_checksum",
    "modify_timestamp",
    "rename_random_section",
    "upx_encryption",
    "action_add_benign_data_overlay_1"
]